/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.Administrador;

import javax.swing.JOptionPane;
import main.ClassCollector;
import modelos.*;

/**
 *
 * @author LEONARDO
 */
public class GestionarUsuario extends javax.swing.JFrame {

    ClassCollector principal;
    boolean rol;

    /**
     * Creates new form GestionarRegion
     */
    public GestionarUsuario(ClassCollector A) {
        initComponents();
        principal = A;
        insertar();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Cusuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CBrol = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Ccontraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Gestionar usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        Cusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(Cusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 200, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Rol");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jPanel1.add(CBrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 200, -1));

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));
        jPanel1.add(Ccontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void insertar() {
        Cusuario.setText("");
        Ccontraseña.setText("");
        CBrol.addItem("Aministrador");
        CBrol.addItem("Empleado");
    }


    private void CusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (Cusuario.getText().trim().isEmpty() || Ccontraseña.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ERROR EN LAS CASILLA", "NO PUEDE HABER CASILLAS EN BLANCO", JOptionPane.INFORMATION_MESSAGE);
        } else {
            boolean repetido = false;

            String rolUsuario = (String) CBrol.getSelectedItem();

            if (rolUsuario.equals("Aministrador")) {
                rol = true;
            } else if (rolUsuario.equals("Empleado")) {
                rol = false;
            }

            for (Usuario u : principal.listaUsuarios) {
                if (u.getUsername().equals(Cusuario.getText()) && u.isManagent() == rol) {
                    repetido = true;
                    break;
                }
            }
            if (repetido) {
                JOptionPane.showMessageDialog(null, "USUARIO REPETIDO ", "ERROR AL REGISTRAR", JOptionPane.INFORMATION_MESSAGE);
            } else {
                Usuario nuevoUsuario = new Usuario(Cusuario.getText(), Ccontraseña.getText(), rol);
                principal.listaUsuarios.insertarFinal(nuevoUsuario);

                JOptionPane.showMessageDialog(null, "REGISTRO EXITOSO", "USUARIO REGISTRADO", JOptionPane.INFORMATION_MESSAGE);
                Cusuario.setText("");
                Ccontraseña.setText("");
                principal.listaUsuarios.mostrarLista();
                
            }
            
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PanelDeControl UU = new PanelDeControl(principal);
        this.setVisible(false);
        UU.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBrol;
    private javax.swing.JPasswordField Ccontraseña;
    private javax.swing.JTextField Cusuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
