/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.Empleado;

import static java.lang.System.exit;
import javax.swing.JOptionPane;

/**
 *
 * @author T800
 */
public class RegistroPasajero extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer RegistroPasajero
     */
    public RegistroPasajero() {
        initComponents();
        this.setVisible(true);
        
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }
    public void limpiar(){
        Cdni.setText("");
        Cnombre.setText("");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Cdni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Cnombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Cfecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Cfecha1 = new javax.swing.JTextField();
        regcliente = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        cancelcli = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMinimumSize(new java.awt.Dimension(510, 393));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("REGISTRAR PASAJERO");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 500, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CdniActionPerformed(evt);
            }
        });
        jPanel1.add(Cdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 142, -1));

        jLabel1.setText("Documento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel5.setText("Nombres y apellidos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 28, -1, -1));

        Cnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnombreActionPerformed(evt);
            }
        });
        jPanel1.add(Cnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 250, -1));

        jLabel6.setText("Destino");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        Cfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CfechaActionPerformed(evt);
            }
        });
        jPanel1.add(Cfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 250, -1));

        jLabel7.setText("Salida");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        Cfecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cfecha1ActionPerformed(evt);
            }
        });
        jPanel1.add(Cfecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 150, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 500, 310));

        regcliente.setText("Registrar");
        regcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regclienteActionPerformed(evt);
            }
        });
        add(regcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 92, -1));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        cancelcli.setText("Cancelar");
        cancelcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelcliActionPerformed(evt);
            }
        });
        add(cancelcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 470, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void CdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CdniActionPerformed

    }//GEN-LAST:event_CdniActionPerformed

    private void CnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CnombreActionPerformed

    private void CfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CfechaActionPerformed

    private void regclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regclienteActionPerformed
        if (Cnombre.getText() != null && Cdni.getText() != null && Cfecha.getText() != null) {
            String nombres = Cnombre.getText();
            
            int dni = Integer.parseInt(Cdni.getText());
            String fecha = Cfecha.getText();
            

        } else {
            JOptionPane.showMessageDialog(this, "Ingrese correctamente los items", "VALIDACION", JOptionPane.ERROR_MESSAGE);
        }
        limpiar();
    }//GEN-LAST:event_regclienteActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void cancelcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelcliActionPerformed
        
    }//GEN-LAST:event_cancelcliActionPerformed

    private void Cfecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cfecha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cfecha1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cdni;
    private javax.swing.JTextField Cfecha;
    private javax.swing.JTextField Cfecha1;
    private javax.swing.JTextField Cnombre;
    private javax.swing.JButton cancelcli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton regcliente;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
